name: MinecraftEras
version: '${project.version}'
main: raffel080108.minecrafteras.MinecraftEras
api-version: 1.19

permissions:
  minecrafteras.*:
    description: Grants all plugin-related permissions
    children:
      minecrafteras.addEraScore:
        description: Grants permission to manually add era-score to the total score
      minecrafteras.depositItem:
        description: Grants permission to deposit items for era-points
      minecrafteras.reload:
        description: Grants permission to reload the plugin
      minecrafteras.removeCampMaster:
        description: Grants permission to remove the camp master
      minecrafteras.spawnCampMaster:
        description: Grants permission to spawn the camp master
      minecrafteras.checkEraScore:
        description: Grants permission to check the current amount of era-score
